-- begin STORE2_ORDER_POSITION
alter table STORE2_ORDER_POSITION add constraint FK_STORE2_ORDER_POSITION_ON_PRODUCT foreign key (PRODUCT_ID) references STORE2_PRODUCT(ID)^
create index IDX_STORE2_ORDER_POSITION_ON_PRODUCT on STORE2_ORDER_POSITION (PRODUCT_ID)^
-- end STORE2_ORDER_POSITION
-- begin STORE2_ORDER
alter table STORE2_ORDER add constraint FK_STORE2_ORDER_ON_CLIENT foreign key (CLIENT_ID) references STORE2_CLIENT(ID)^
create unique index IDX_STORE2_ORDER_UNIQ_ORDER_NUMBER on STORE2_ORDER (ORDER_NUMBER)^
create index IDX_STORE2_ORDER_ON_CLIENT on STORE2_ORDER (CLIENT_ID)^
-- end STORE2_ORDER
-- begin STORE2_PRODUCT
create unique index IDX_STORE2_PRODUCT_UNIQ_NAME on STORE2_PRODUCT (NAME)^
-- end STORE2_PRODUCT
-- begin STORE2_ORDER_POSITION_ORDER_LINK
alter table STORE2_ORDER_POSITION_ORDER_LINK add constraint FK_ORDPOSORD_ON_ORDER foreign key (ORDER_ID) references STORE2_ORDER(ID)^
alter table STORE2_ORDER_POSITION_ORDER_LINK add constraint FK_ORDPOSORD_ON_ORDER_POSITION foreign key (ORDER_POSITION_ID) references STORE2_ORDER_POSITION(ID)^
-- end STORE2_ORDER_POSITION_ORDER_LINK
